### ISSUE TITLE
parse helper for java.util.Date

### ISSUE THREAD

**Issue by waywardmonkeys** [derekjw/fyrie-redis#3]
It would be nice to have a .parse[Date] available ... easy to do with Long values with new Date(Long) and Date.getTime() returning a Long.

**Comment by derekjw** [comment]
Sure, I can add that. Just to be sure, since I didn't document it, you can always create your own instances of Store and Parse for whatever types you'd like to use. As long as they are implicitly available.

**Comment by derekjw** [comment]
Added Parse and Store instances for Date in branch 'akka-1.1'
