### ISSUE TITLE
health check for RedisClient

### ISSUE THREAD

**Issue by waywardmonkeys** [derekjw/fyrie-redis#4]
I'd like a way to check the health of a redis client.  It should verify that it can talk successfully with the server.  This is something I would use in monitoring using the HealthCheck class from Coda Hale's Metrics.

**Comment by derekjw** [comment]
Would this be as simple as performing a PING command and getting a response?

**Comment by waywardmonkeys** [comment]
Yes, but ping does not currently work ... I'll file an issue about that and close this one.
